### ISSUE TITLE
Add terms and conditions text

### ISSUE THREAD

**Issue by molebox** [Rebuild-Black-Business/RBB-Website#112]
Add a link to the terms page

**Comment by M0nica** [comment]
is this available?

**Comment by magnificode** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add terms and conditions text](https://trello.com/c/eIVPzYQw/95-add-terms-and-conditions-text)

**Comment by magnificode** [comment]
#180 solves this issue!
