### ISSUE TITLE
No Display after search

### ISSUE THREAD

**Issue by wcouturiaux** [Rebuild-Black-Business/RBB-Website#199]
On the business page, if a `business type` is selected, a `location` entered, and `In Urgent Need` selected, when search executes nothing displays below in the `iframe class=airtable-embeded`

**Comment by wcouturiaux** [comment]
Displays form to add new business if no `business type` selected

**Comment by racedale** [comment]
I get the form doing that 
<img width="1245" alt="Screen Shot 2020-06-11 at 9 55 48 AM" src="https://user-images.githubusercontent.com/6390640/84402228-cdef2700-abc9-11ea-92d6-332427414845.png">

**Comment by wcouturiaux** [comment]
Displayed properly after clearing my cache.
