### ISSUE TITLE
Hide pagination when no business are matched in search

### ISSUE THREAD

**Issue by devmrin** [Rebuild-Black-Business/RBB-Website#211]
On the `/businesses` page upon search if no businesses are matched - the pagination should be hidden. 

Screenshot for reference: 
![image](https://user-images.githubusercontent.com/26342387/84420961-79cf5b80-ac38-11ea-893a-ce06df6c5936.png)

**Comment by juanri0s** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [On Business Page we need to hide pagination when no business are matched in search.](https://trello.com/c/WDpG3UVE/202-on-business-page-we-need-to-hide-pagination-when-no-business-are-matched-in-search)
