### ISSUE TITLE
Logo very pixelated on 4k desktop screen

### ISSUE THREAD

**Issue by beattheprose** [Rebuild-Black-Business/RBB-Website#212]
The heading site logo looks quite pixelated on my 4k display. The issue seems to persist across all pages. Please see below for example:

![image](https://user-images.githubusercontent.com/45179933/84421546-54fbc980-abe1-11ea-9a4e-536580bc78a5.png)

The issue also shows up at mobile size:

![image](https://user-images.githubusercontent.com/45179933/84421730-9be9bf00-abe1-11ea-8627-0ca598f42ae9.png)

**Comment by beattheprose** [comment]
Tested on Brave, Chrome, and Firefox

**Comment by juanri0s** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Blurry Logo in Nav](https://trello.com/c/vzuJfTqd/107-blurry-logo-in-nav)
