### ISSUE TITLE
Create ResultCard component structure

### ISSUE THREAD

**Issue by magnificode** [Rebuild-Black-Business/RBB-Website#22]
Trello: https://trello.com/c/g5OZn1z8

The ResultCard has two variations:

### ResultCard Default State

![Screen Shot 2020-06-05 at 10 50 53 AM](https://user-images.githubusercontent.com/1380536/83902977-98a28f00-a71a-11ea-8aef-f4c791e40928.png)

The ResultCard default state should output the following data from Airtable:
- Business Image - Does not exist in Airtable currently, read on.
  - Use image if available. If no image available, pull from fallback asset for the business category.
  - This data _does not_ currently exist in the database. Write conditionals to prepare for this, leverage a random unsplash image https://source.unsplash.com/random as a stub for the fallback.
- Business Name
- Business Category
- Business Blurb
  - This data _does not_ currently exist in the database. Write conditionals to prepare for this.
- Business Location
- Business Buttons
  - 1 - 2 buttons
  - Website URL button text dependent on business category
    - Entertainment: Learn more
    - Food and beverage: Order
    - Health and wellness: Learn more
    - Professional services: Contact
    - Retail: Shop
  - If no donate URL, the Website button takes full width.
  - If there is a donate URL provided, second button appears to the right, with button text “Donate”
- Report Link
  - mailto: link, use placeholder email for now.

### ResultCard Basic

![Screen Shot 2020-06-05 at 11 00 29 AM](https://user-images.githubusercontent.com/1380536/83903667-c6d49e80-a71b-11ea-83bd-be89772f0142.png)

This variation does not utilize a Business image, but instead leverages a background color.

- Business Name
- Business Location
- Business Blurb
  - This data _does not_ currently exist in the database. Write conditionals to prepare for this.
- Business Button
  - 1 Button
  - Website URL. Button text "Website"
- Report Link
  - mailto: link, use placeholder email for now.

**Comment by chancestrickland** [comment]
On it

**Comment by magnificode** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create "ResultCard" component](https://trello.com/c/g5OZn1z8/34-create-resultcard-component)

**Comment by chancestrickland** [comment]
Starting out with a generic, composable set of `Card` components. You can opt in or out to any of the sub components pretty easily, and override whatever you need on the sub-component itself. Later this evening I'll circle back here and abstract this into a higher-level API for the result card.

```js
function Layout() {
  return (
    <Grid templateColumns="repeat(2, 1fr)" gap={6} ml={10}>
      <CardWrapper>
        <CardImage src="https://picsum.photos/900/900" />
        <CardContent bg="lightgray">
          <CardHeading>Ultrices vehicula cubilia euismod</CardHeading>
          <CardText>
            Urna ad aliquet taciti dapibus rutrum morbi iaculis ut, lacinia sit
            luctus leo posuere montes torquent, mi ligula lacus inceptos
            pharetra vitae augue.
          </CardText>
          <CardButtonGroup>
            <CardButton>Click Me</CardButton>
            <CardButton>Click Me Too</CardButton>
          </CardButtonGroup>
        </CardContent>
      </CardWrapper>
      <CardWrapper>
        <CardContent bg="#424242" color="white">
          <CardHeading>Ultrices vehicula cubilia euismod</CardHeading>
          <CardText>
            Urna ad aliquet taciti dapibus rutrum morbi iaculis ut, lacinia sit
            luctus leo posuere montes torquent, mi ligula lacus inceptos
            pharetra vitae augue.
          </CardText>
          <CardButtonGroup>
            <CardButton>Click Me</CardButton>
            <CardButton>Click Me Too</CardButton>
          </CardButtonGroup>
          <Text as="p" fontSize="sm" fontStyle="italic" mt={3}>
            Velit gravida est senectus mollis nunc adipiscing nulla magna nec
          </Text>
        </CardContent>
      </CardWrapper>
    </Grid>
  );
}
````

![image](https://user-images.githubusercontent.com/3082153/83913397-42d2e480-a724-11ea-89e2-d8902b2dd532.png)
