### ISSUE TITLE
Review & Update ReadMe

### ISSUE THREAD

**Issue by racedale** [Rebuild-Black-Business/RBB-Website#223]
go over the readme and update it since so much has changed over the past few days leading up to launch. 

- Remove Discord Invite Link
- Maybe remove links to Trello
- Update terminology

**Comment by M0nica** [comment]
I took a first-pass at updating the README to remove links that should no longer be included and direct people to sign up at http://join.rebuildblackbusiness.com/. https://github.com/Rebuild-Black-Business/RBB-Website/pull/261

**Comment by magnificode** [comment]
This was merged with #261 - Thank you @M0nica!

@racedale - if there are more specific terminology changes that you want to add let's open a new issue and document those changes specifically. Going to close this out for now!
