### ISSUE TITLE
Use Link component only for internal links

### ISSUE THREAD

**Issue by racedale** [Rebuild-Black-Business/RBB-Website#229]
Resolve this warning from Chakra UI: 
`External link https://www.instagram.com/clay.banks was detected in a Link component. Use the Link component only for internal links.`

**Comment by M0nica** [comment]
This is interesting because Chakra has examples where the Link is an external link 🤔  https://chakra-ui.com/link#external-link

**Comment by M0nica** [comment]
Oh I see the Chakra was wrapping Gatsby Link which explains why external links weren't supported
