### ISSUE TITLE
Create filtering and sorting logic

### ISSUE THREAD

**Issue by magnificode** [Rebuild-Black-Business/RBB-Website#24]
### Business Filtering

![Screen Shot 2020-06-05 at 11 08 43 AM](https://user-images.githubusercontent.com/1380536/83904346-ed470980-a71c-11ea-9605-7c5ba60f4129.png)

Filters should be created to allow a user to filter results from the [BusinessInNeedFeed](https://github.com/Rebuild-Black-Business/RBB-Website/blob/master/src/components/Feeds/BusinessInNeedFeed.js) component by the following criteria:

- Business Type
  - Label: "Business"
  - Type: single select
    - Options: "Entertainment", "Food and beverage", "Health and wellness", "Professional services", "Retail"
  - Placeholder: "Select type"

- Location
  - Label: "Location"
  - Type: text
    - Allow users to type their city. i.e "Denver" should return any business who's location includes "Denver".
  - Placeholder: "Enter city"

- Need
  - Label: "Need"
  - Type: single select
    - For V1 this should be a "disabled" field that pre-populates with an "Impacted by protests" option.
    - For V1 this select field _will not_ affect filtered results. The business filters will _only_ display businesses in need.

- Submit
  - Type: submit
  - Label: "Search"
  - On click of the submit button **or** on 'enter', the filtered results should appear below the filters without a page refresh.

### Resource Filtering

![Screen Shot 2020-06-05 at 11 19 21 AM](https://user-images.githubusercontent.com/1380536/83905147-698e1c80-a71e-11ea-95a7-03d8ca16a4fd.png)

Filters should be created to allow a user to filter results from the [SupportingOrgFeed](https://github.com/Rebuild-Black-Business/RBB-Website/blob/master/src/components/Feeds/SupportingOrgFeed.js) component by the following criteria:

- Resources For
  - Type: single select
    - Options: "Ally", "Business owner"
  - Label: "Resources for"
  - Placeholder: "Who are you?"

- Location
  - Label: "Location"
  - Type: text
    - Allow users to type their city. i.e "Denver" should return any business who's location includes "Denver".
  - Placeholder: "Enter city"

- Submit
  - Type: submit
  - Label: "Search"
  - On click of the submit button **or** on 'enter', the filtered results should appear below the filters without a page refresh.

### Ally Filtering
![71cb190824b43e77781da33212907e42](https://user-images.githubusercontent.com/1380536/83924050-d4e8e600-a740-11ea-830b-1d44277ad0c1.png)

- Skill
  - Type: single select
  - Label: "Skill" 
  - Placeholder text: "What do you need?"
  - Options: 
    - Business
    - Marketing
    - Outreach
    - Tech
    - Government

- Location
  - Label: "Location"
  - Type: text
    - Allow users to type their city. i.e "Denver" should return any ally who's location includes "Denver".
  - Placeholder: "Enter city"

- Submit
  - Type: submit
  - Label: "Search"
  - On click of the submit button **or** on 'enter', the filtered results should appear below the filters without a page refresh.

### Filter Results

The results should be dynamically updated upon user hitting "Search" or hitting "return" on their keyboard as any normal form would.

**IMPORTANT** :: Accessibility needs to be top of mind for the results, please refer to https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions to ensure that live updated regions are properly announced to screen readers.

**Comment by ryancharris** [comment]
Got it 👍

**Comment by magnificode** [comment]
@ryancharris - Added expectations for the filter results, along with important accessibility considerations. This one is a beast, so if you need to recruit a friend to help out with the a11y bits please don't hesitate to do so.

**Comment by ryancharris** [comment]
@magnificode Sounds good. I'm planning on breaking the two components into separate PRs to make them easier to review. I will also be using Chakra components where possible, so we can reduce the a11y issues. I'll ask some folks who have more a11y experience than I do to review 👍

**Comment by magnificode** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create Feed filtering component and functionality](https://trello.com/c/htXVUBxL/36-create-feed-filtering-component-and-functionality)

**Comment by ryancharris** [comment]
@magnificode In this PR, I will also update the theme config to include our "primary buttons"

**Comment by ChrisBrownie55** [comment]
Thought this might help:

```js
function filter(nodes, filters) {
  return nodes.filter(({ data }) => {
    let isMatch = true
    for (const filterName in filters) {
      isMatch = isMatch && data[filterName] === filters[filterName]
    }
    return isMatch
  })
}

// Used like so:
function SupportingOrgs({ data }) {
  const nodes = filter(data.allAirtableSupportOrgs.nodes, { Category: 'Business', Location: 'Oakland, CA' })
  // of course you'll want to replace the values above with user input
}
```

The only thing that might need to be improved is the checking to see for matches. Might make more sense to use a RegExp to allow for partial matches.
