### ISSUE TITLE
Show "no results" card in businesses only when api returns empty array and not on initial page load.

### ISSUE THREAD

**Issue by Mhmdabed11** [Rebuild-Black-Business/RBB-Website#247]
In the `/businesses` page, the no results card is shown on page load for a small amount of time then the results cards are displayed. On the initial load, maybe a skeleton loader should exist while making the api call to get the search results.

**Comment by M0nica** [comment]
It looks to me like this was resolved? On initial load of /businesses I no longer see the no results card before results load.

**Comment by magnificode** [comment]
@M0nica This has indeed been resolved in our switch to our custom API in #263. Appreciate you bringing this to our attention @Mhmdabed11!
