### ISSUE TITLE
Some "Learn More" links are broken

### ISSUE THREAD

**Issue by psalaets** [Rebuild-Black-Business/RBB-Website#264]
# Steps

1. Load https://www.rebuildblackbusiness.com/businesses in any browser (I tried FF, Safari and Chrome on macOS)
2. Scroll down to the card for "Wild Haven Botanica LLC"
3. Click the "Learn More" button

## Expected

User ends up at https://www.wildhavenbotanica.com

## Actual

User ends up at https://www.rebuildblackbusiness.com/www.wildhavenbotanica.com

# More details

Seems like some of the business urls in your data (in airtable?) are being treated as relative links because they don't start with the protocol.

## Screenshot

<img width="626" alt="business url treated as relative url" src="https://user-images.githubusercontent.com/123952/85341192-9af43f80-b4b5-11ea-8737-08b0fecb513b.png">

**Comment by psalaets** [comment]
Ran this on all 5 pages of the business list

```js
[...document.querySelectorAll('a[href]')]
   .map(a => a.attributes.href.value)
   .filter(href => href.startsWith('www'))
   .join('\n')
```

And found 5 urls that need attention

- www.kentuckygreensco.com
- www.blacksoilky.com
- www.thoselovelylocks.com
- www.wildhavenbotanica.com
- www.framedglenwood.com

Also, the url for www.framedglenwood.com has a single trailing space in your data

**Comment by elchris** [comment]
@psalaets i just fixed these 5 in AirTable, and I also created a new view on AirTable called "Broken Website Field" which shows all records whose Website field is:

- not null
- does not contain http://
- does not contain https://

and there are over 240 of them so i'm just going thru the list. As I clean things up, updated data should show-up on the site within 2 hours

**Comment by psalaets** [comment]
Looks good to me, thanks
