### ISSUE TITLE
Establish desired data to collect for new businesses

### ISSUE THREAD

**Issue by magnificode** [Rebuild-Black-Business/RBB-Website#267]
## The Context

We are using an embedded Airtable form to collect information when a new business is registered on the site. Currently we are asking businesses to provide the following information (* denotes a required field):

- Your First Name *
- Your Last Name *
- Your Email *
- Business Name *
- Category *
- Business Description *
- Business Website
- Business has a physical location
  - If the above is true: Zip Code *
- Business has been directly affected by recent events
  - If the above is true: Donation Link (optional)

## The Problem

As it stands we are able to provide _rough locations_ for businesses based on their Zip Code. To aid in our goals for V1, we want to be able to more accurately and effectively help users find these businesses. We also want to structure our data such that we can leverage precise location data in future feature releases.

## The Solution

Establish the data we want to collect, a couple items that have been suggested are:

- Physical Address
- Business Image / Logo

The data structure will need to be modified to ingest this new data so that we can properly request this data on the Front End for upcoming feature work.

**Comment by llexical** [comment]
Added the backend required flag largely to make it easier for me to keep an eye on @elchris and @brentmclark probs interested in this as well :)

**Comment by elchris** [comment]
To aid in validation:
        /*
         * https://maps.googleapis.com/maps/api/place/findplacefromtext/json
         * ?key=
         * &inputtype=textquery
         * &fields=business_status,formatted_address,geometry,icon,name,photos,place_id,plus_code,types
         * &input=BUSINESS+NAME+in+ZIPCODE
         */

Documentation:

- Costs: https://developers.google.com/places/web-service/usage-and-billing#find-place
  - $0.017 per call
  - $0.00 for "Basic Data" returned:
    - https://developers.google.com/places/web-service/usage-and-billing#basic-data
- Specs: https://developers.google.com/places/web-service/search#FindPlaceRequests

- This API Endpoint returns exactly one result, or an empty "candidates" array if nothing found
- The "fields" list above falls within Google's "Basic Data" List, which is "no additional cost".
  - it includes latitude and longitude
- This could be useful for two angles, with a single API call we could:
  - Validate that the business does exist at that zip code, so we can decide whether or not to ask of the user that they correct their input
  - Extract the business's Lat and Long

**Comment by magnificode** [comment]
@llexical @elchris @brentmclark - Check out the figma designs here: https://www.figma.com/file/Lo1ZcBOO9t4QRbX2I0PwBQ/RBB?node-id=1938%3A8027

These are _fairly_ close to final, but still need to be run by the Business team and Justin for their approval. This should give us at least a good idea of what the design / UX team are looking to implement for business submissions.

Once we get the approval from Business, I'd love to schedule a time to chat with you folks to discuss the implications that these forms may have on our data structure!

**Comment by magnificode** [comment]
@llexical @elchris I have updated the production Airtable to reflect the design changes that Neil finished up.

I'm going to go ahead and close this issue out, seeing as we have established the data structure and can move on to actually implementing this on the FE.
