### ISSUE TITLE
Add individual pages for each business listing

### ISSUE THREAD

**Issue by magnificode** [Rebuild-Black-Business/RBB-Website#268]
## Prerequisites
- [x] #267 :: The data structure needs to be solidified before we create these pages
- [x] Design for the profile page
- [x] [Backend endpoint to get a single building](https://trello.com/c/ZPKR6jit/37-add-endpoint-for-getting-a-business-by-id) 

## Designs
https://www.figma.com/file/Lo1ZcBOO9t4QRbX2I0PwBQ/RBB?node-id=2135%3A1
https://www.figma.com/file/Lo1ZcBOO9t4QRbX2I0PwBQ/RBB?node-id=2135%3A363

## The Problem

Currently users are only able to explore businesses found on the RBB site by the small amount of information we provide on the `ResultCard` components. We want to enable businesses to provide a wider range of information that we can leverage on a 'profile' page for each business.

## The Solution

We need to dynamically create a "Business Profile" template for each business in the database. Additionally, we need to conditional _all the things_ to account for our legacy data that will have much of this data missing, or incomplete. The page needs to be flexible enough to account for if the majority of this information is not available.

**Comment by elchris** [comment]
For calling the API:

in the search results, you will notice that each record has a field called "id" which is an integer.

this is the field that you can plug into an individual business data request:

https://api.rbb-api.com/api/v1/businesses/13557
