### ISSUE TITLE
[Feature] "online only" option for businesses for users

### ISSUE THREAD

**Issue by ashtine** [Rebuild-Black-Business/RBB-Website#278]
## Prerequisites
- [x] #267 
- [ ] Filter design and architecture needs to be established before this can be worked on

## User Story

As a user
I want to see only online businesses
So I can contribute to those businesses specifically

## Acceptance Criteria
- [ ] There is an online only option in the filter
- [ ] When I use the filter I see only online businesses
- [ ] The rest of the page works as expected

## Is your feature request related to a problem? Please describe.
There a businesses who are online only and want to show that + users who want to see those options

## Describe the solution you'd like
A filter with an online businesses only option

**Comment by llexical** [comment]
We will need backend work here to make sure that any Airtable field we add to store if a business is online or not is passed through to our search API and that it can be searched by.

**Comment by magnificode** [comment]
There will be a new ticket we will use to track redesigned filter changes. Closing this for now.
