### ISSUE TITLE
[Feature] Add UTM to urls for Businesses

### ISSUE THREAD

**Issue by ashtine** [Rebuild-Black-Business/RBB-Website#280]
## User Story
As a business owner on RBB
I want to I want to see where traffic is coming from
So I can know how we're getting exposure

## Acceptance Criteria
- [ ] All external links to businesses include `utm_source=Rebuild+Black+Business` as query string
- [ ] Any link that already includes a query string properly has the UTM code appended.

## Is your feature request related to a problem? Please describe.
Add a tracking code to the end of any business URL so that the businesses themselves can see who is coming to their site from RBB

## Describe the solution you'd like
Dynamically append UTM tracking code to URLs with and without existing query params

**Comment by JTSchwartz** [comment]
I'd be happy to work on this feature
