### ISSUE TITLE
[BUG] Get rid of the flash that happens when loading the website

### ISSUE THREAD

**Issue by ashtine** [Rebuild-Black-Business/RBB-Website#281]
**Describe the bug**
The flash that happens when loading the website

**To Reproduce**
1. Go to rebuildbackbusiness.com
2. Observe

**Expected behavior**
No flash and looks clean

**Actual Behavior**
A flash and kinda clunky

**Screenshots**
![Screen Capture on 2020-06-26 at 16-20-49](https://user-images.githubusercontent.com/25046304/85897853-2e38b800-b7c9-11ea-87fe-8817aa893300.gif)

**Comment by ifyoumakeit** [comment]
I can take a crack at this, it looks like we can get a lot of mileage out of preloading the fonts and the hero image using meta tags in the <head />. Resizing the hero image using `srcSet` to fit will also speed up the site and remove the flash of it loading. 

Can use some dynamic URLS from cloudinary for srcSet https://cloudinary.com/documentation/responsive_images

**Comment by ifyoumakeit** [comment]
Actually looking into it more, it looks like the hero image doesn't load without JavaScript.

**Comment by magnificode** [comment]
@ifyoumakeit it might be useful to work with @domitriusclark on this one! Preloading fonts and other assets as best we can is a great idea as well. Feel free to move on what you can, and work with Dom on the image stuff in particular! I'll assign this task to you and him for now!

**Comment by ifyoumakeit** [comment]
> @ifyoumakeit it might be useful to work with @domitriusclark on this one! Preloading fonts and other assets as best we can is a great idea as well. Feel free to move on what you can, and work with Dom on the image stuff in particular! I'll assign this task to you and him for now!

Sounds good!

**Comment by magnificode** [comment]
@ifyoumakeit - @domitriusclark merged a few updates to the Cloudinary Image component today #299 . Not sure if that helps this issue, but figured I'd keep you updated :).

Anything we can do to help with this issue let us know!

**Comment by JapneetSingh5** [comment]
Hi, I would love to contribute to your site. Can i comtribute to this issue or anywhere else you may need?

**Comment by ifyoumakeit** [comment]
> @ifyoumakeit - @domitriusclark merged a few updates to the Cloudinary Image component today #299 . Not sure if that helps this issue, but figured I'd keep you updated :).
> 
> 
> 
> Anything we can do to help with this issue let us know!

Thanks for the update, I’ll see if this helps here.

**Comment by magnificode** [comment]
I think we've handled what we can with this issue at this point. We may want to consider creating a new task to add a loader to the site that will wait for all assets to load before animating the site in. Closing for now, we can create a new issue down the line for a loader if we wish!
