### ISSUE TITLE
[Feature] Replace Mailto: links

### ISSUE THREAD

**Issue by ashtine** [Rebuild-Black-Business/RBB-Website#282]
## User Story
As a user
I want to see an actual form when contacting someone
So I can feel it is more secure

## Acceptance Criteria
- [ ] No mailto: links on site
- [ ] Any inline mailto: link is replaced with a modal containing a custom "contact" web form
- [ ] The web form contains `Name`, `Email Address`, and `Message` fields.
- [ ] Forms work as expected when used

## Is your feature request related to a problem? Please describe.
mailto: links are easily scraped and tend to not be a super secure way to display email data.

## Describe the solution you'd like
A modal should be created that contains a custom built web form using Gatsby + Netlify form integration as explained here: https://www.gatsbyjs.org/docs/building-a-contact-form/#netlify

The web form will be a very generic form that we can use to capture requests of all types.

**Comment by magnificode** [comment]
@ThugDebugger @shapirone - We need to document places on the site where these mailto links exist. Currently I believe most of the mailto: links are leveraged on the Allies page. Beyond that, I believe that most of the mailto: links are leveraged in content, referencing either business@ or eingineering@ email address. Will the above generic form be enough for these cases?

**Comment by ElishebaW** [comment]
@ashtine Are you thinking to have this form pop up for each ally? Where the email button currently is?
<img width="259" alt="Screen Shot 2020-07-12 at 11 58 27 AM" src="https://user-images.githubusercontent.com/20779752/87251067-04bd9480-c437-11ea-9012-411ef25dda7e.png">

**Comment by shapirone** [comment]
Sorry I didn't get to this @magnificode  but yes @ElishebaW , this form should pop for the Email buttons on the Allies page, the General Inquiry card on the About page, the Email icon in the footer, and any links in the 404 page.

Those are all the spots I know of but we should no longer have any links using mailto on the site, so please double check with a quick project search for `mailto:` for any other instances I may have missed.

**Comment by magnificode** [comment]
Hey @ElishebaW - sorry to have such a late reply in this issue, but were you interested in taking this task? No worries if too much time has passed and your availability has changed :). Just want to make sure I don't pass this off before checking with you!

**Comment by magnificode** [comment]
Going to close this issue out for now. We will eventually be refactoring Allies and how they are integrated into the system in the near future.
