### ISSUE TITLE
[Feature] Add verbiage to explain business review process

### ISSUE THREAD

**Issue by magnificode** [Rebuild-Black-Business/RBB-Website#285]
## Prerequisites
- [x] Content from Business around this process

## User Story
As a business owner
I want to know what the process is to get my business added to the site
So I can anticipate how long to wait before I see it on the site

## Acceptance Criteria
- [ ] When submitting a business there should be a link to an informational page that describes the RBB Business submission process.
- [ ] New page for business submission process created.

## Is your feature request related to a problem? Please describe.
Businesses are somewhat left in the dark currently about what the review process is like, and how long it may take to see their business on the site.

## Describe the solution you'd like
At a low level I think we just need to add wording above business submit forms that explains this process. The content that should exist on this page is as follows:

-----

#### Business Vetting Process

You’re thinking of submitting a Black-Owned Business for inclusion into our database.  Terrific news, we are always looking out for more businesses to join us.  Here is what our process is:
You can submit a business for inclusion into our database, clicking the Register a Business button to display the registration form.

There are several fields that we need you to fill out. It is essential that you fill out as many fields as possible; doing so will allow us to approve your submission fastest.

Once we receive your application, someone from the Business Team will review your form and double-check the information you have provided.  This can include visiting your website, calling the phone number you have provided, and conducting internet searches. Once your information has been verified, they will then approve your business for inclusion into the database.

If we are unable to successfully verify your business, we will send you an email message asking for additional information.
We here at Rebuild Black Business operate on a trust and honor system. This means that our directory is for Black-owned Businesses only. If you submit a business for inclusion into our directory, we will take you at your word that your submission is for a Black-Owned Business. This will stand true unless we receive any information to the contrary.

For online businesses only, we understand that you operate a company that may not be bound to a physical location, and you can service customers around the world.  However, we do ask you for the Zip Code of the area that you operate out of.  Many visitors would like to support not only Black-Owned businesses, but if it is locally based to their location that adds an additional level of satisfaction for them. As such, we request that you include your Zip Code.

If you have questions, please email us at social@rebuildblackbusiness.com.

**Comment by agbanusi** [comment]
HI @magnificode so you basically want two pages, one displaying the business vetting process and another with a form to fill in the details?
