### ISSUE TITLE
[Feature] Remove Allies Info from Allies page

### ISSUE THREAD

**Issue by ashtine** [Rebuild-Black-Business/RBB-Website#288]
## User Story
As an ally
I want to have my information protected
So I can have peace of mind 

## Acceptance Criteria
- [ ] The  ally cards are no longer present
- [ ] The information is still stored an able to be used for those seeking allies

## Is your feature request related to a problem? Please describe.
This came up due to the possibility of these names getting scarped with their info and used for maybe not good purposes. We want to Allies to be able to connect to the community, but in a different way.

## Describe the solution you'd like
Allies moves to the resources page and when a user needs an ally in specific industry, we can provide a resource taking on new people (still working through what v1 for this will be)

## Other
New designs will be needed to show what this will look like

**Comment by magnificode** [comment]
We have established that our conversion of Allies to Resources is likely not going to make it into V1. Our focus will remain on Business architecture for now.
