### ISSUE TITLE
[Feature] Create "Fundraisers" page

### ISSUE THREAD

**Issue by magnificode** [Rebuild-Black-Business/RBB-Website#289]
## Prerequisites
- [x] Design

Figma Designs: https://www.figma.com/file/Lo1ZcBOO9t4QRbX2I0PwBQ/RBB?node-id=2008%3A105

## User Story
As a user
I want to view a page that only shows fundraisers
so I can quickly view ways to support black owned business

## Acceptance Criteria
- [ ] A new top level Fundraisers page should be added to the top level navigation
- [ ] Businesses that have a "Donate" entry in the database should be pulled out of the Business Listing feed, and shown on the newly created "Fundraisers" page.
- [ ] Businesses that have a "Donate" entry in the database must also show in the main business listing page.

## Describe the solution you'd like
We want to highlight businesses in need without them getting lost in the entire business directory. Separating Businesses with a "Donate" link from the main business listing page should help with this.

**Comment by Mhmdabed11** [comment]
I can start on this issue if nothing is on hold!

**Comment by magnificode** [comment]
@Mhmdabed11 that would be excellent, thank you so much!

**Comment by Mhmdabed11** [comment]
@magnificode 
![image](https://user-images.githubusercontent.com/39762577/90382956-2807df00-e088-11ea-9274-3682de371279.png)
I have a list of questions regarding this issue: 
- Where can I find the public Id of the image above
- What should happen when the button in the card above is pressed?
- Currently I am fetching businesses using a Graphql query on Airtable businesses collection . I cannot find the location/state attribute which should show in the fundraiser card.

**Comment by elchris** [comment]
Please don’t query AirTable directly, use our REST API for this:

https://api.rebuildblackbusiness.com/

Use the “Find Businesses” GET endpoint:

https://api.rbb-api.com/api/v1/businesses?in-need=true

And be sure to pass the x-api-key header whose value should come from a local .env file , which in your dev environment can be your personal api key from the portal and in production will be automatically replaced with our production key. You can see the code example from the main “See Businesses” site.

**Comment by Mhmdabed11** [comment]
Okay @elchris  thank you for your input !!

**Comment by magnificode** [comment]
Merged in #321
