### ISSUE TITLE
[Feature] Custom tables for ally and business sign up

### ISSUE THREAD

**Issue by SeHarlan** [Rebuild-Black-Business/RBB-Website#295]
## User Story
Removing Airtable iframe embeds

## Describe the solution you'd like
Creating custom table that link to the Airtable API so the forms fit visually with the rest of the website

**Comment by SeHarlan** [comment]
I will start on this, Probably will get it done by end of day on Tuesday ( June 30th )

**Comment by magnificode** [comment]
Closed by #297
