### ISSUE TITLE
Create Button component and variations

### ISSUE THREAD

**Issue by magnificode** [Rebuild-Black-Business/RBB-Website#30]
### Buttons

Figma: https://www.figma.com/file/Lo1ZcBOO9t4QRbX2I0PwBQ/RBB?node-id=2%3A102

Buttons should extend existing Chakra UI components to achieve the style outlined in the figma document for each state and variation.

**Comment by ChrisBrownie55** [comment]
Jumping on it 👍

**Comment by ChrisBrownie55** [comment]
Done! https://github.com/Rebuild-Black-Business/RBB-Website/pull/34

**Comment by ChrisBrownie55** [comment]
I now realize that there's another PR that was put out for this (didn't see the Trello and claimed here, sorry). However, I think the PR I put up is a bit more configurable and uses the `<Button>` component from ChakraUI internally instead of just `<PseudoBox>` which has less functionality built into it (`<Button>` uses `<PseudoBox>` internally).

**Comment by magnificode** [comment]
@ChrisBrownie55 I am so so sorry, I hadn't had a chance to assign this to the person who had the ticket in progress as they had not been invited to the GitHub org yet (jumped into meetings directly after I created it).

We have in progress work happening via this PR https://github.com/Rebuild-Black-Business/RBB-Website/pull/23 - is there any chance you can work with them to see what we can do about leveraging any of the work you've done here?

This is 100% on me for not finishing this ticket out completely before creating it, so sorry for the confusion.

**Comment by magnificode** [comment]
> I now realize that there's another PR that was put out for this (didn't see the Trello and claimed here, sorry). However, I think the PR I put up is a bit more configurable and uses the `<Button>` component from ChakraUI internally instead of just `<PseudoBox>` which has less functionality built into it (`<Button>` uses `<PseudoBox>` internally).

I'd love for you to collaborate with the folks working on that ticket! If leveraging `<Button>` over `<PseudoBox>` is more flexible then we definitely want to consider it. Andy has been super receptive to feedback!

**Comment by ChrisBrownie55** [comment]
Will do, thank you, sorry about the confusion.

**Comment by magnificode** [comment]
@ChrisBrownie55 no need to apologize at all. On me for trying to juggle too many things at once :)
