### ISSUE TITLE
[BUG] Menu unusable on Safari

### ISSUE THREAD

**Issue by racedale** [Rebuild-Black-Business/RBB-Website#304]
**Describe the bug**
On mobile Safari some of the home page elements are rendering above the menu

**To Reproduce**
1. Go to 'home page
2. Click on menu
3. See error

**Expected behavior**
Menu should load the same as Chrome and Firefox

**Screenshots**
![image0](https://user-images.githubusercontent.com/6390640/87729105-1a72e700-c7b4-11ea-884a-757feb4b5657.png)

**Comment by JTSchwartz** [comment]
Looks like this isn't just limited to Safari, but I think I've identified the cause of it. I'd be happy to take care of this, just need to make sure my fix doesn't break something else
