### ISSUE TITLE
[Feature] Update link styles across the site

### ISSUE THREAD

**Issue by magnificode** [Rebuild-Black-Business/RBB-Website#314]
## User Story
As a user
I want to see consistent link styles across the site

## Acceptance Criteria
- [ ] Ensure all link styles throughout the site match the brand guidelines defined here: https://www.figma.com/file/Lo1ZcBOO9t4QRbX2I0PwBQ/RBB?node-id=2022%3A4381

## Describe the solution you'd like
We need to make sure that all text link styles match the designs outlined above, for both light and dark background colors.

**Comment by AdrianTNare** [comment]
i'll take this one .

**Comment by magnificode** [comment]
Thanks a ton @AdrianTNare - Let me know if you have any questions or concerns!

**Comment by magnificode** [comment]
Hey @AdrianTNare - wanted to check in here real quick and see if there was anything I could do to help, or if you had any questions about the task!

**Comment by AdrianTNare** [comment]
hey, @magnificode, I only have one question so far: will these changes affect all the different types of Links that we have, or do they only apply to our custom Link component?

**Comment by magnificode** [comment]
@AdrianTNare this should affect all links for consistency throughout the site. Thanks for checking in, let me know if you need anything else!
