### ISSUE TITLE
[BUG] Responsive Design of Business Listing

### ISSUE THREAD

**Issue by wcouturiaux** [Rebuild-Black-Business/RBB-Website#325]
**Describe the bug**
Business names are moving letter by letter to a new line as page size changes. 

**To Reproduce**
1. Go to https://www.rebuildblackbusiness.com/businesses?location=detroit,%20michigan
2. Scroll down until you see the listing.
3. Manually resize the browser width to 1247px
4. Gradually increase the width to 1280px plus.

**Expected behavior**
Entire word moves to the next line when resizing would force a letter from the end.

**Actual Behavior**
For this particular business, it is on one line with a browser width of 1248px-1279px (either side of that range it moves letter by letter to a new line until 1589+ px the last letter is left hanging on its own line.

**Screenshots**
![image](https://user-images.githubusercontent.com/37006112/90851843-e60ac180-e343-11ea-9c95-a1263f0f8cfa.png)

**Comment by wcouturiaux** [comment]
I also noticed the location for this seems to be wrong according to their website.

**Comment by magnificode** [comment]
@wcouturiaux - appreciate the bug submission and info, we'll get this queued up to be fixed ASAP!

**Comment by mbifulco** [comment]
If someone wants to tackle this, it should be a [relatively straightforward CSS fix ](https://css-tricks.com/almanac/properties/o/overflow-wrap/)- `good first issue` material!

Feel free to @ me here or on Discord if you'd like help 👍
