### ISSUE TITLE
[BUG] Fix Warnings/Errors in Dev Console on Business Page

### ISSUE THREAD

**Issue by juanri0s** [Rebuild-Black-Business/RBB-Website#346]
**Describe the bug**
"Failed prop type: Invalid prop `loadingState` of type `string` supplied to `BusinessFeed`, expected `object`." in BusinessFeed (at businesses.js:185)

"Failed prop type: Invalid prop `category` of type `object` supplied to `ResultCard`, expected `string`." in ResultCard (at BusinessFeed.js:51)

"Failed prop type: Invalid prop `location` of type `string` supplied to `ResultCard`, expected `number`." in ResultCard (at BusinessFeed.js:51)

"Use the `defaultValue` or `value` props on `<select>` instead of setting `selected` on `<option>`." in option (at BusinessFilter.jsx:77)

**To Reproduce**
1. Open dev console
2. Go to /businesses
3. See warnings/errors

**Expected behavior**
No warnings/errors

**Actual Behavior**
Errors/Warnings

**Screenshots**

**Comment by saraogipraveen** [comment]
Hi, @juanri0s I want to take this up.
