### ISSUE TITLE
[Feature] Make homepage landing searchable

### ISSUE THREAD

**Issue by ThugDebugger** [Rebuild-Black-Business/RBB-Website#353]
## User Story
As a user
I want to search for a black owned business through the home page
So I can quickly find the information I'm looking for without having to navigate to another page.

## Acceptance Criteria
- [ ] Search bar, and associated header indicating that a user can search for black owned businesses
- [ ] On submit, the user is taken to the business page, with their query shown and results ready/pending
- [ ] More or less, think of this like the google home page 

## Is your feature request related to a problem? Please describe.
It is not always immediately clear to users that they can search for black owned businesses on our site. We want to prioritize this functionality and make it apparent as soon as a user lands on the home page.

## Describe the solution you'd like
We want the user to hit the homepage and instantly have the ability to search for black-owned businesses w/o having to click around. This will lead to a better user experience by giving the user what they want in a quicker fashion. An easy approach to this could be to have a styled search box on our homepage that when a user enters their search, their values are transferred over to the "Business" search page via Query String Params, and immediately executed on page load with the data.

**Comment by brentmclark** [comment]
I can take this one.
