### ISSUE TITLE
[BUG] "Register A Business" Form: Make Protocol Mandatory on ALL URLs

### ISSUE THREAD

**Issue by elchris** [Rebuild-Black-Business/RBB-Website#379]
**Describe the bug**
When filling out information to Register a Business, a user is still allowed to enter URLs without a protocol. We must enforce that client side.

**To Reproduce**
1. Go here https://www.rebuildblackbusiness.com/businesses
2. Click on 'Register a Business'
3. Scroll down to 'Website'
4. Notice that while it suggests that you enter a protocol, it does not **enforce it**
5. Check the box that says "Business has an ongoing donation campaign"
6. Notice the same issue with "Donation Link" field

**Expected behavior**
No form should be allowed to be submitted without all URLs having a protocol in front of them

**Actual Behavior**
www.foo.com is allowed and 99% of the time what people put in there.

**Epilogue and Broader Context**
- Note that this should be a low-hanging quick fix to the issue at hand, and very-much well worth doing.
- Eventually this work could be further improved by implementing #323 
  - We could keep the input form exactly the same, but instead of submitting to AirTable, it would submit to the RBB API with the following benefits:
    - The API gives back helpful and detailed validation messages when certain conditions are not met
    - We can stop leaking our AirTable API Credentials in the client side code and http requests. This is **not** a good place to be.

**Comment by brianjhanson** [comment]
I can take a look at this one
