### ISSUE TITLE
Implement Formik and Yup for forms and validation

### ISSUE THREAD

**Issue by brianjhanson** [Rebuild-Black-Business/RBB-Website#384]
[Formik](https://formik.org/docs/overview) mixed with [Yup](https://github.com/jquense/yup) provide a great developer experience as well as pave the way for more complex validation which leads to a better user experience and more consistent data flowing to the API. We should add them and use them for the forms on the site and expand on the work done in #381

**Comment by magnificode** [comment]
Closed by #381

**Comment by brianjhanson** [comment]
Hey @magnificode #381 didn't actually add this. That one implements some custom validation which is probably less than ideal. My original goal was to make it a bit more solid with this ticket.
