### ISSUE TITLE
README Backend Dev Trello Link Broken

### ISSUE THREAD

**Issue by juanri0s** [Rebuild-Black-Business/RBB-Website#39]
Not sure if it's not set up yet or maybe the name changed, but the backend trello link in the README leads to a 'Board Not Found' error https://trello.com/b/034hEV4X/rebuild-black-business-backend-dev

**Comment by andrewchough** [comment]
This link should work: https://trello.com/invite/b/034hEV4X/7c7810342e79aa410ebf8158c209ceeb/rebuild-black-business-backend-dev

Although I'm not sure if we want to change the README to this link too

**Comment by brewswain** [comment]
Couldn't help but notice that this issue is still up. May I suggest that if we don't want the backend link exposed in the README then we simply say to request access to the trello board in the Discord's backend channel?

**Comment by juanri0s** [comment]
link words now, closing
