### ISSUE TITLE
Create a utility function to convert ZIP codes from database into City, ST format.

### ISSUE THREAD

**Issue by magnificode** [Rebuild-Black-Business/RBB-Website#43]
### Zip Codes

One of the primary goals of the RBB site is to ensure that we can quickly and effectively connect people with black owned businesses near them. In order to do this, we do our best to accurately generate location based data for users to filter by.

Currently in the DB we are collecting zip codes of businesses that have a storefront. Some businesses do not have a storefront and are therefore tagged as an "Online" business.

If a business has a storefront, we need to take their zip code, and display it as "City, ST" on the frontend. For example, a business has the zip code of 80219, the front end should display "Denver, CO".

This should be a utility function that we can pass an integer to, and have it return the "City, ST" format.

Explore using https://www.npmjs.com/package/zipcodes - this has features that we would like to leverage in the future as well.

**Comment by magnificode** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create a utility function to convert ZIP code integers into City, ST strings.](https://trello.com/c/YZMUtWv2/40-create-a-utility-function-to-convert-zip-code-integers-into-city-st-strings)

**Comment by brewswain** [comment]
Hey, I can get started on making this.

**Comment by mbifulco** [comment]
Hey @brewswain sorry I didn't see you were going to tackle this! Have at it - I just assigne it to you on trello as well.  If you need help, drop me a line on Discord 👍

**Comment by brewswain** [comment]
Oh sweet, no problem! I think it was actually my fault since I didn't do it from trello first, so thanks!
