### ISSUE TITLE
Create Footer

### ISSUE THREAD

**Issue by magnificode** [Rebuild-Black-Business/RBB-Website#44]
### Footer

Figma: https://www.figma.com/file/Lo1ZcBOO9t4QRbX2I0PwBQ/RBB?node-id=429%3A57

__Desktop__
![footer](https://user-images.githubusercontent.com/1380536/83953216-a7ad3e00-a7fb-11ea-8112-7d3a90a8022c.png)

__Mobile__
![footermob](https://user-images.githubusercontent.com/1380536/83953431-a2e98980-a7fd-11ea-8de0-cbf111bb42f2.png)

The Footer component will be added to our `<Layout />` component (https://github.com/Rebuild-Black-Business/RBB-Website/blob/master/src/components/Layout.js) and should appear on every page. It is composed of a few sections:

**Social List**

Individual social icons for various social media properties. For now stub these out with `#` as the `href` until we have these properties 100% set up. On hover or focus of each icon, increase size by 10%:

`transform: scale(1.1)`

**Link List**

Below the social icons is the link list, this should be the _same_ as the link list in the navigation. A `<StaticQuery>` should be used to generate this link list. See https://github.com/Rebuild-Black-Business/RBB-Website/blob/master/src/components/Layout.js#L17 and https://github.com/Rebuild-Black-Business/RBB-Website/blob/master/src/components/PrimaryNav.js#L62 for how we're building this in the PrimaryNav component.

**Photo Credits**

The assets we use on the site are all public domain, and thus must be attributed to the photographer who took the pictures. The `menuLinks` object within `siteMetadata` here: https://github.com/Rebuild-Black-Business/RBB-Website/blob/master/gatsby-config.js#L33 should be expanded to include the Photographer's name, and URL on a per page basis.

The only photo credits we have approved are the Home page credits:

```
John Cameron https://unsplash.com/@john_cameron
Kelly Lacy https://instagram.com/kellymlacy
Mike Von thevoncomplex.com
```

The photo credit should open in a new tab.

**Copyright Information**

The copyright year in the footer should be dynamic and the "Terms and Conditions" bit should be a link to a (currently not created) "Terms and Conditions" page. The text for Terms and Conditions should contain non-breaking spaces so that it does not wrap in the middle on smaller screens.

Ensure all links can be tab targeted and include focus states.

**Comment by magnificode** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create "Footer" component](https://trello.com/c/Onmqcg5h/41-create-footer-component)

**Comment by molebox** [comment]
Id be happy to take this
