### ISSUE TITLE
Create ContentBlock component and variations

### ISSUE THREAD

**Issue by magnificode** [Rebuild-Black-Business/RBB-Website#45]
### ContentBlock

Figma: https://www.figma.com/file/Lo1ZcBOO9t4QRbX2I0PwBQ/RBB?node-id=429%3A57

Leveraging Chakra UI components, we need to build out a ContentBlock component that can accept a few parameters in order to output the different variations on the home page.

**Customization Options**

The content block should be a single Higher Order Component that allows us to add any content within it. Primarily this content will be Headings, Paragraphs, and Buttons.

As a Developer, I should be able to customize the background color that is used on an individual block and whether it is a fade, or tint.

As a Developer I should be able to customize the image that appears as the background for this block.

As a Developer I should be able to choose to have the text appear on the left, right or in the center of the block.

**Customization Examples**

__Left aligned content, black background that fades over a custom img src, Heading, Paragraph, and 2 Buttons as children of the Higher Order Component.__

_Desktop_
![ContentBlock--Left--Black](https://user-images.githubusercontent.com/1380536/83953855-3bcdd400-a801-11ea-87b1-5ee475b2b409.png)

__Right aligned content, white background that fades over a custom img src, Heading, Paragraph with an inline link, and 2 buttons as children of the Higher Order Component__ 

_Desktop_

![ContentBlock--Right--White](https://user-images.githubusercontent.com/1380536/83953870-5dc75680-a801-11ea-97e5-3e322e3d1a68.png)

__Center aligned content, color tint over a custom img src, Paragraph, and one button that spans the width of the content__

![ContentBlock--Center](https://user-images.githubusercontent.com/1380536/83953899-936c3f80-a801-11ea-84a3-38b4534df7c5.png)

### Responsive

The ContentBlock should be responsive, the content will center, span the full width, and the background color will become a tint over the background image on smaller screens

_Mobile_
![ContentBlock--Left--Black-mobile](https://user-images.githubusercontent.com/1380536/83954041-d1b62e80-a802-11ea-83b2-798243f2683e.png)

**Comment by magnificode** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create "ContentBlock" component](https://trello.com/c/GX6chK1w/42-create-contentblock-component)

**Comment by aka-tpayne** [comment]
I’ll have some ramp up to do with Chakra but I’ll take a stab at this.

**Comment by magnificode** [comment]
@aka-tpayne thank you very much! Don't hesitate to reach out in the Discord if you have issues. I'm sure someone would be happy to pair on this if you need it!
