### ISSUE TITLE
Layout About Page

### ISSUE THREAD

**Issue by racedale** [Rebuild-Black-Business/RBB-Website#47]
Figma: https://www.figma.com/file/Lo1ZcBOO9t4QRbX2I0PwBQ/RBB?node-id=429%3A57

Leveraging Chakra UI components and already existing ContactCard components, we need to layout the home page to match up to UI designs. H2 headers should be used for "who we are", "mission", and "contact" headers

_Trello_: 
https://trello.com/c/TeFxrCVb/43-about-page

Image Assets:
- Cloudinary ID for Fist image: assets/people-protesting-on-street-4552840_gginry
- Cloudinary ID for Contact image1: assets/contact-left
- Cloudinary ID for Contact image2: assets/contact-middle
- Cloudinary ID for Contact image3: assets/contact-right

_Desktop_: 
![RBB-about](https://user-images.githubusercontent.com/6390640/83957181-56ca3380-a855-11ea-9bf2-438480544d9e.png)

### Responsive
The layout should be responsive, the content will center, span the full width.

_Mobile_:
![RBB-about-mobile](https://user-images.githubusercontent.com/6390640/83957183-5b8ee780-a855-11ea-9c85-a558a3100fd4.png)

**Comment by juanri0s** [comment]
I can pick this item up for tonight.

I'm somewhat newish to react so if I don't finish, I don't mind someone else continuing in the morning. Will make sure to leave any details before going to bed.

**Comment by asaki444** [comment]
@juanri0s and I worked on the contact cards, making it responsive.

When adding width to the parent Flex on the about page, it causes the mobile site to left align all cards. To fix, I added `margin: 2% auto` to center the cards, and add spacing in between.

**Comment by juanri0s** [comment]
Couple of notes:

- "Add your business to our list" - opens a modal, what fields are we expecting (we don't have mockups or flows for this yet)? Or are we just focused on the general layout and styling of the about page as part of the task. 
- "General inquiry" - Do we still want this opening the default mail app? I know sometimes this isnt a good practice. 
- The about background image isn't a card so it doesn't have the cloudinary stuff, is this part of the task or is someone else going to do the implementation?
- As noted in the trello task, "Likely want to utilize the ContentBlock component, may need to be done as tech debt if that story isn't ready". I don't believe this is ready

**Comment by racedale** [comment]
[Image](https://res.cloudinary.com/rebuild-black-business/image/upload/v1591504323/image_1_p51pbo.jpg)

- don't worry about adding the interactions yet, first step is just lay it out.
> As noted in the trello task, "Likely want to utilize the ContentBlock component, may need to be done as tech debt if that story isn't ready". I don't believe this is ready although I see the task

Exactly, if it isn't ready it'll have to be refactored later

**Comment by magnificode** [comment]
@juanri0s don't worry about using the ContentBlock component here. Just use basic ChakraUI components for the text.

Appreciate the thoroughness!

**Comment by racedale** [comment]
- Cloudinary ID for Fist image: `assets/people-protesting-on-street-4552840_gginry`
- Cloudinary ID for Contact image1: `assets/allison-christine-wV7UfVeI84w-unsplash_y3xvql`
- Cloudinary ID for Contact image2: `assets/RTJIXQNne68_ry3yib`
- Cloudinary ID for Contact image3: `assets/concours-discord-cartes-voeux-fortnite-france-6_1_xifoxc`
