### ISSUE TITLE
Create Pagination Component

### ISSUE THREAD

**Issue by racedale** [Rebuild-Black-Business/RBB-Website#48]
## Pagination
Figma: https://www.figma.com/file/Lo1ZcBOO9t4QRbX2I0PwBQ/RBB?node-id=579%3A1516

Leveraging Chakra UI components, we need to build out a Pagination component that can support having optional ellipsis for large amounts of pages of results. 

- Given a user is on the first page + 4 more (5 pages total), the first set of ellipsis will not be shown.
<img width="363" alt="Screen Shot 2020-06-06 at 10 47 19 PM" src="https://user-images.githubusercontent.com/6390640/83959954-95a5bc80-a848-11ea-8efe-badb834096d6.png">

- Given a user is on the last page - 4 less (5 pages total), the first set of ellipsis will not be shown. 
<img width="595" alt="Screen Shot 2020-06-06 at 10 54 10 PM" src="https://user-images.githubusercontent.com/6390640/83959958-aa825000-a848-11ea-8648-eb9e95bfa9f1.png">

- Given a user is somewhere in the "middle" of the results (not the previous two scenarios) then the 
middle number will be active and both sets of ellipsis will be shown
<img width="598" alt="Screen Shot 2020-06-06 at 10 46 31 PM" src="https://user-images.githubusercontent.com/6390640/83959871-9f7af000-a847-11ea-863b-5b027b06ac69.png">

Mobile:
<img width="613" alt="Screen Shot 2020-06-06 at 10 53 12 PM" src="https://user-images.githubusercontent.com/6390640/83959963-b66e1200-a848-11ea-808d-f10c2bc5ab54.png">

**If it's quick to add**, support desktop version as well. If not it's lower priority and should be created as a separate Issue, so notify @racedale & @magnificode 
Desktop:
<img width="688" alt="Screen Shot 2020-06-06 at 10 16 50 PM" src="https://user-images.githubusercontent.com/6390640/83959642-f6cb9100-a844-11ea-9336-3127628bd612.png">

**Comment by racedale** [comment]
Trello card: https://trello.com/c/zxR8G4LA/44-create-pagination-component

**Comment by billy-le** [comment]
I would like to take this one.

**Comment by magnificode** [comment]
@racedale are we good to close this out since #49 is merged?
