### ISSUE TITLE
Contact Interactions on About Page

### ISSUE THREAD

**Issue by racedale** [Rebuild-Black-Business/RBB-Website#51]
## Contact Section

AC: 
Given a user clicks:
- Business owners: then open a blank Chakra modal (content added in later story)
- General Inquiry:  mailto: (email to be provided later)
- Volunteers: Discord link (join.rebuildblackbusiness.com)

Desktop:
<img width="1077" alt="Screen Shot 2020-06-07 at 11 23 32 AM" src="https://user-images.githubusercontent.com/6390640/83974232-77c07200-a8b1-11ea-9c29-1aa6ce9092fd.png">

Mobile:
<img width="290" alt="Screen Shot 2020-06-07 at 11 24 59 AM" src="https://user-images.githubusercontent.com/6390640/83974238-8ad34200-a8b1-11ea-8f05-d0b511538170.png">

**Comment by M0nica** [comment]
I want to work on this once https://github.com/Rebuild-Black-Business/RBB-Website/issues/47  is wrapped up by @asaki444

**Comment by billy-le** [comment]
Hi @M0nica I see that you assigned and then unassigned yourself from this task. Did you still want to take this on?

**Comment by M0nica** [comment]
> Hi @M0nica I see that you assigned and then unassigned yourself from this task. Did you still want to take this on?

I’m still interested in working on this task and am awaiting #47 to be finished but I also don’t want to be a blocker if I’m not available to start as soon as #47 is done.

**Comment by billy-le** [comment]
@M0nica okay, that shouldn't be a problem. I won't jump on this. Thanks!

**Comment by juanri0s** [comment]
I added some comments for this in the Trello task. I'm not too sure that this task is needed or it just needs to be updated to include other work needed in the About page.
