### ISSUE TITLE
Create BusinessFilter Component

### ISSUE THREAD

**Issue by magnificode** [Rebuild-Black-Business/RBB-Website#52]
### BusinessFilter

Since data structure has been finalized we can now work on getting the BusinessFilter functionality wired up. Here's the logic:

As a user, I should be able to optionally filter businesses by category. This field should incorporate the following:

**Field type:** dropdown select
**Field label:** Business
**Field placeholder option:** Select type
**Dropdown options:** 
- Entertainment
- Food and beverage
- Health and wellness
- Professional services
- Retail

As a user, I should be able to optionally filter businesses by City / State OR Zipcode. By leveraging [this NPM package](https://www.npmjs.com/package/zipcodes) we should be able to take in "Atlanta, GA" for example, return an array of zip codes that are associated with that city state string, and return results that match any zip in that array

**Field type:** Text search (likely will need strict validation to ensure the "Atlanta, GA" format. Searching "Atlanta" or "ATL" will not yield any results in v0). This will accept **both** city state, or a zip code.

**Field label:** Location
**Field placeholder text** : Eg. "Atlanta, GA" or "30301"

As a user, I should be able to filter businesses by their level of need. This is a boolean value in the database. Businesses impacted by current events will be labelled as "In Need" in the database.

**Field type:** Checkbox (Should be pre-checked for v0)
**Field Label:** "In Immediate Need" (this is subject to change as designs are fully approved)

**Comment by magnificode** [comment]
@ryancharris will be tackling this

**Comment by mbifulco** [comment]
This was closed by #55
