### ISSUE TITLE
Match PrimaryNav to updated designs

### ISSUE THREAD

**Issue by magnificode** [Rebuild-Black-Business/RBB-Website#59]
### PrimaryNav

Figma: ~https://www.figma.com/file/Lo1ZcBOO9t4QRbX2I0PwBQ/RBB?node-id=427%3A1426~
https://www.figma.com/file/Lo1ZcBOO9t4QRbX2I0PwBQ/RBB?node-id=1156%3A6458

The alignment of the navigation items, and some small stylistic changes need to be reflected in the code. Changes include:

- Addition of a "Subscribe" button (using our current button components which were merged in #34 )
  - On mobile, the subscribe button should span the full width of the navigation container, and the button text should be centered.
  - **Functionality** When a user clicks on this Subscribe button, a Modal (https://chakra-ui.com/modal) should pop up. For this task we can leverage dummy content within the modal.
- Primary navigation items should now be aligned left
- Background color of the nav should now be our `black-000` variable

**Comment by M0nica** [comment]
@magnificode I have a few questions:
- where can the subscribe link be found? 
- is the left aligned change only on desktop view before the menu toggles?

**Comment by magnificode** [comment]
@M0nica - Ah my fault, let me update the issue to include what the functionality for that subscribe button actually is.

Just to answer the question in this comment too, the Subscribe button will trigger a modal that will include a Mailchimp embedded newsletter form. For this task, if you are able to add the Modal trigger using https://chakra-ui.com/modal - that would be excellent. You can place dummy content in the modal for now. We'll place the mailchimp embed form in once we have it.

The left aligned change is for both desktop and mobile, the Figma design linked above should give you a clear picture of the approved layout!

Let me know if that answers your question!

**Comment by magnificode** [comment]
@M0nica Trello task for extra reference if you need as well! https://trello.com/c/VauipPfZ/54-update-navigation-alignment

**Comment by magnificode** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update Navigation alignment](https://trello.com/c/VauipPfZ/54-update-navigation-alignment)

**Comment by M0nica** [comment]
I’m working on this in this branch: https://github.com/Rebuild-Black-Business/RBB-Website/tree/feature/enhancePrimaryNavDesign

**Comment by M0nica** [comment]
Latest designs: https://www.figma.com/file/Lo1ZcBOO9t4QRbX2I0PwBQ/RBB?node-id=1156%3A6458
