### ISSUE TITLE
Create Pagination logic

### ISSUE THREAD

**Issue by magnificode** [Rebuild-Black-Business/RBB-Website#63]
### Pagination

Leverage `gatsby-node.js` to create a pre-filtered page of data per each of the 50 states. This will create some nice SEO opportunities to have a URL per state of black owned businesses. It will also allow us to properly categorize data that does not have complete information, and ensure that they can still be included and searched for on the site.

**Comment by jbolda** [comment]
Another option is the split it up by category, but I think that will be partly dependent on how the quantity of data of each is split up.

**Comment by mbifulco** [comment]
@magnificode looks like this can be closed.  Great work @jbolda!
