### ISSUE TITLE
Layout Home Page

### ISSUE THREAD

**Issue by racedale** [Rebuild-Black-Business/RBB-Website#72]
Figma: https://www.figma.com/file/Lo1ZcBOO9t4QRbX2I0PwBQ/RBB?node-id=0%3A1

Leveraging Chakra UI components and already existing ContentBlock and PrimaryButton components, we need to layout the home page to match up to UI designs. 

_Trello_: 
https://trello.com/c/UfKtiYcc/11-layout-homepage-content

Image Assets:
- Cloudinary ID for Fist image: `assets/home-header-bg`
- (Alternate) Cloudinary ID for Fist image: `assets/home-header-bg-space`
- Cloudinary ID for Contact image1: `assets/cta1-bg`
- Cloudinary ID for Contact image2: `assets/cta2-bg`
- (Alternate) Cloudinary ID for Contact image2: `assets/cta2-bg-space`
- Cloudinary ID for Contact image3: `assets/cta3-bg`

_Desktop_: 
<img width="363" alt="Screen Shot 2020-06-07 at 11 38 35 AM" src="https://user-images.githubusercontent.com/6390640/84092769-04f0ed00-a9be-11ea-9956-bf1615c32b03.png">

### Responsive
The layout should be responsive, the content will center, span the full width.

_Mobile_:
<img width="107" alt="Screen Shot 2020-06-07 at 11 38 47 AM" src="https://user-images.githubusercontent.com/6390640/84092777-07534700-a9be-11ea-8948-11eb61f6dd38.png">

**Comment by magnificode** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Layout homepage content](https://trello.com/c/UfKtiYcc/11-layout-homepage-content)
