### ISSUE TITLE
Add Loading component when switching between pages

### ISSUE THREAD

**Issue by magnificode** [Rebuild-Black-Business/RBB-Website#82]
### Loading

Because of the amount of data we are presenting to users, we want to be sure that between perceived page loads, any component that has to fetch data (<AllyFeed /> and <BusinessFeed /> for example) should present a `<Loading />` component.

A simple Chakra UI spinner will suffice for this task https://chakra-ui.com/spinner

**Comment by molebox** [comment]
Be happy to take this 😊

**Comment by domitriusclark** [comment]
We could also make use of the `Skeleton` component for individual component loading states. 

Pretty sure we can change background/color/etc 

Just a thought

**Comment by magnificode** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add loading component when switching between pages](https://trello.com/c/2w1nMD89/61-add-loading-component-when-switching-between-pages)

**Comment by molebox** [comment]
On it if available
