### ISSUE TITLE
Add gating functionality to the Allies page

### ISSUE THREAD

**Issue by magnificode** [Rebuild-Black-Business/RBB-Website#85]
### Ally Page Gating

Figma Desktop: https://www.figma.com/file/Lo1ZcBOO9t4QRbX2I0PwBQ/RBB?node-id=1155%3A9992
Figma Mobile: https://www.figma.com/file/Lo1ZcBOO9t4QRbX2I0PwBQ/RBB?node-id=1155%3A10056

When a user visits the Allies page for the first time, they should be presented with a popup asking them to agree to our terms and conditions (link TBD). Upon checking the checkbox, the modal will be closed, and the AllyFeed will be rendered.

Functionally, we want to prevent easy scraping of our user's data. So in order to help cut down on that we require folks to accept terms and conditions before they view the list. We need to ensure that *no data* is shown until the terms and conditions have been clicked, instead, behind this modal we will show a grid of "Skeleton" elements (https://chakra-ui.com/skeleton). Once the checkbox has been clicked, localStorage should be used to ensure that user does not have to accept the terms and conditions again, the modal should close, and the Skeleton elements should be re-rendered with real data.

**Comment by magnificode** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Allies] - Add gating functionality](https://trello.com/c/DJGlxKd4/55-allies-add-gating-functionality)

**Comment by kieranklaassen** [comment]
I can take this one. Let me know
